version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  ApplicationStop:
    - location: kill_container.sh
      timeout: 20
      runas: ec2-user
  AfterInstall:
    - location: after_install.sh
      timeout: 120
      runas: ec2-user
  ApplicationStart:
    - location: start_container.sh
      timeout: 180
      runas: ec2-user