version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 30
      runas: ec2-user
  ApplicationStop:
    - location: kill_container.sh
      timeout: 20
      runas: ec2-user
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start_container.sh
      timeout: 300
      runas: ec2-user