version: "3"

services:
  app:
    build: .
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_IMAGE_REPO_NAME}:${AWS_IMAGE_TAG}
    container_name: test-app
    restart: always
    ports:
      - "80:8080"
    logging:
      driver: awslogs
      options:
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-group=myLogGroup
        # or create logGroup (formation, console) and pass a env var then awslogs-create-group can be deleted
        awslogs-create-group=true